version: "3.3"

services:
  website:
    build: .
    ports:
      - "8720:8000"
    volumes:
      - "staticfiles:/app/static"
      - type: "bind"
        source: "/data/www/sutazeStrom/db.sqlite3"
        target: "/app/db.sqlite3"
      - type: "bind"
        source: "/data/www/sutazeStrom/.secrets"
        target: "/app/.secrets"
    restart: always

  static:
    image: "nginx:1.23"
    depends_on:
      - "website"
    ports:
      - "8721:80"
    volumes:
      - "staticfiles:/usr/share/nginx/html:ro"
    restart: always

volumes:
  staticfiles:
