name: Deploy to Production

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: sutazeStrom
      - uses: wshihadeh/docker-deployment-action@v2
        with:
          remote_docker_host: webstrom@server.strom.sk
          ssh_private_key: ${{ secrets.WEBSTROM_DEPLOY_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.WEBSTROM_DEPLOY_SSH_PUBLIC_KEY }}
          stack_file_name: sutazeStrom/compose.yaml
          args: up --build --force-recreate --detach
